export const ActionTypes = {
    FETCH_ALL_MOVIE_DETAILS_REQUEST: 'FETCH_ALL_MOVIE_DETAILS_REQUEST',
    FETCH_ALL_MOVIE_DETAILS_SUCCESS: 'FETCH_ALL_MOVIE_DETAILS_SUCCESS',
    FETCH_ALL_MOVIE_DETAILS_ERROR: 'FETCH_ALL_MOVIE_DETAILS_ERROR'
}